twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        sitename: 'CSEIM-Nabeul'
#        images_directory: '%kernel.project_dir%/public/uploads/'